# ===== Application Info =====
spring.application.name=spring-di-lab
app.version=1.0.0
app.description=Aplikasi latihan Week 3 - IoC & DI

# ===== Server Configuration =====
server.port=8080

# ===== Custom App Config =====
app.greeting.default-name=Mahasiswa
app.greeting.prefix=Selamat datang
app.notification.max-retry=3

# ===== Logging =====
logging.level.root=INFO
logging.level.com.example.springdilab=DEBUG

spring.profiles.active=dev